openapi: 3.2.0
info:
  title: Board Foresight API - V1 Enumeration API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: Enumeration
  description: ''
paths:
  /aggregationmethods:
    get:
      tags:
      - Enumeration
      description: The complete list of aggregation methods in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get aggregationmethods
      x-summary-source: derived
      operationId: getAggregationmethods
      x-operation-id-source: derived
  /calculations:
    get:
      tags:
      - Enumeration
      description: The complete list of calculations in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get calculations
      x-summary-source: derived
      operationId: getCalculations
      x-operation-id-source: derived
  /frequencies:
    get:
      tags:
      - Enumeration
      description: The complete list of frequencies which may be applied to an Indicator in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get frequencies
      x-summary-source: derived
      operationId: getFrequencies
      x-operation-id-source: derived
  /seasonalities:
    get:
      tags:
      - Enumeration
      description: The complete list of seasonalities which may be specified for an Indicator in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get seasonalities
      x-summary-source: derived
      operationId: getSeasonalities
      x-operation-id-source: derived
  /forecastmodeltypes:
    get:
      tags:
      - Enumeration
      description: The complete list of forecast model types which may be specified for a Forecast Model in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get forecastmodeltypes
      x-summary-source: derived
      operationId: getForecastmodeltypes
      x-operation-id-source: derived
  /classifications:
    get:
      tags:
      - Enumeration
      description: The complete list of classifications which may be applied to an Indicator in the system.
      responses:
        '200':
          description: OK
        '429':
          description: If the user has sent too many requests
      summary: Get classifications
      x-summary-source: derived
      operationId: getClassifications
      x-operation-id-source: derived
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
