openapi: 3.2.0
info:
  title: Board Foresight API - V1 Forecast Model History API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: ForecastModelHistory
  description: ''
paths:
  /forecastmodelhistory/{ForecastModelId}:
    get:
      tags:
      - ForecastModelHistory
      description: Retrieves the forecast model's history
      parameters:
      - name: ForecastModelId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ForecastModelHistory'
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastModelHistory'
            text/json:
              schema:
                $ref: '#/components/schemas/ForecastModelHistory'
        '422':
          description: Model is expired or in a non-production state
        '429':
          description: If the user has sent too many requests
      summary: Get forecastmodelhistory by forecast model id
      x-summary-source: derived
      operationId: getForecastmodelhistoryByForecastModelId
      x-operation-id-source: derived
components:
  schemas:
    Seasonality:
      enum:
      - 0
      - 1
      - 999
      type: integer
      format: int32
    ContributionResult:
      type: object
      properties:
        forecast:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Point'
        componentContributions:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IndicatorValues'
      additionalProperties: false
    PeriodAlignment:
      enum:
      - 0
      - 1
      - 2
      type: integer
      format: int32
    Frequency:
      enum:
      - 0
      - 1
      - 2
      - 4
      - 12
      - 52
      - 365
      - 1000
      type: integer
      description: 'The frequency of the data.



        Daily: 365



        Weekly: 52



        Monthly: 12



        Quarterly: 4



        SemiAnnual: 2



        Annual: 1'
      format: int32
    AggregationMethod:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    Point:
      type: object
      properties:
        value:
          type: number
          format: double
        date:
          type: string
          format: date-time
        annotation:
          type:
          - string
          - 'null'
        manuallyAdjusted:
          type: boolean
        isForecasted:
          type:
          - boolean
          - 'null'
      additionalProperties: false
    CoefficientInfo:
      type: object
      properties:
        indicatorKey:
          $ref: '#/components/schemas/IndicatorKey'
        value:
          type: number
          format: double
      additionalProperties: false
    SegmentInfo:
      type: object
      properties:
        segment:
          type: integer
          format: int32
        intercept:
          type: number
          format: double
        coefficients:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CoefficientInfo'
          description: Component coefficients ordered by indicator offset
      additionalProperties: false
    ProviderAccess:
      enum:
      - 0
      - 1
      - 2
      type: integer
      format: int32
    IndicatorType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      type: integer
      format: int32
    IndicatorKey:
      type: object
      properties:
        provider:
          type: string
          description: The ID of the provider for the indicator.
          format: uuid
        providerId:
          type:
          - string
          - 'null'
          description: The provider id of the indicator.
      additionalProperties: false
      description: The provider:providerId pair. This is used to identify an indicator in the system.
    Calculation:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      type: integer
      description: 'The transformation applied to the data.



        Possible options:



        None 1



        PeriodOverPeriod 2



        YearOverYear 3



        ThreePeriodYearOverYear 6'
      format: int32
    ForecastModelIteration:
      type: object
      properties:
        forecastModelName:
          type:
          - string
          - 'null'
        forecastModelId:
          type: string
          format: uuid
        forecastModelType:
          $ref: '#/components/schemas/ForecastModelType'
        forecastModelCalculation:
          $ref: '#/components/schemas/Calculation'
        executionTime:
          type: string
          format: date-time
        fitAndForecast:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Point'
          description: Forecast Model output values with no calculation applied and trimmed using regression start and as of dates
        primaryValues:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Point'
          description: Time series data of Primary Indicator with no calculation applied
        components:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ComponentInformation'
          description: Model components, excluding user specified indicators, ordered by offset
        segments:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SegmentInfo'
        contributionResult:
          $ref: '#/components/schemas/ContributionResult'
      additionalProperties: false
    IndustryCode:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
      additionalProperties: false
    DisplayInformation:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: The display name to be used in the application. Limited to 50 characters.
        description:
          type:
          - string
          - 'null'
          description: The description to be shown in the application. Limited to 1,000 characters.
        color:
          type:
          - string
          - 'null'
          description: The color to use in the application. Must be a valid hex color code.
        category:
          type:
          - string
          - 'null'
          description: The category of the indicator. Limited to 1,000 characters.
      additionalProperties: false
    Indicator:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        aggregate:
          $ref: '#/components/schemas/AggregationMethod'
        calculation:
          $ref: '#/components/schemas/Calculation'
        color:
          type:
          - string
          - 'null'
        displayInformation:
          $ref: '#/components/schemas/DisplayInformation'
        count:
          type: integer
          format: int32
        created:
          type: string
          format: date-time
        startTime:
          type:
          - string
          - 'null'
          format: date-time
        endTime:
          type:
          - string
          - 'null'
          format: date-time
        transformedStartTime:
          type:
          - string
          - 'null'
          format: date-time
        transformedEndTime:
          type:
          - string
          - 'null'
          format: date-time
        frequency:
          $ref: '#/components/schemas/Frequency'
        deprecated:
          type: boolean
        deprecationReason:
          type:
          - string
          - 'null'
        lastModified:
          type: string
          format: date-time
        provider:
          $ref: '#/components/schemas/Provider'
        providerId:
          type:
          - string
          - 'null'
        seasonality:
          $ref: '#/components/schemas/Seasonality'
        source:
          type:
          - string
          - 'null'
        classification:
          $ref: '#/components/schemas/Classification'
        tags:
          type:
          - array
          - 'null'
          items:
            type: string
        type:
          type:
          - string
          - 'null'
        units:
          type:
          - string
          - 'null'
        accessibility:
          $ref: '#/components/schemas/ProviderAccess'
        periodAlignment:
          $ref: '#/components/schemas/PeriodAlignment'
        path:
          type:
          - string
          - 'null'
        notes:
          type:
          - string
          - 'null'
        citation:
          type:
          - string
          - 'null'
        dataSources:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IndicatorDataSource'
        industryCodes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IndustryCode'
        hasZeroVariance:
          type:
          - boolean
          - 'null'
        interval:
          type:
          - string
          - 'null'
        countryCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    IndicatorValues:
      type: object
      properties:
        indicator:
          $ref: '#/components/schemas/Indicator'
        leadTime:
          type: integer
          format: int32
        values:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Point'
      additionalProperties: false
    ComponentInformation:
      type: object
      properties:
        deprecated:
          type: boolean
        name:
          type:
          - string
          - 'null'
        provider:
          type: string
          format: uuid
        providerId:
          type:
          - string
          - 'null'
        offset:
          type: integer
          format: int32
        values:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Point'
      additionalProperties: false
    ForecastModelType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: 'None: 0



        Rocet: 1



        Multivariate: 2



        SegmentedMultivariate: 3



        WeightedUnivariateRegression: 4


        '
      format: int32
    IndicatorDataSource:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        url:
          type:
          - string
          - 'null'
        dataSourceType:
          $ref: '#/components/schemas/IndicatorType'
      additionalProperties: false
    Provider:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        source:
          type:
          - string
          - 'null'
      additionalProperties: false
    Classification:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      type: integer
      format: int32
    ForecastModelHistory:
      type: object
      properties:
        captureDate:
          type: string
          format: date-time
        forecastModelIteration:
          $ref: '#/components/schemas/ForecastModelIteration'
      additionalProperties: false
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
