openapi: 3.2.0
info:
  title: Board Foresight API - V1 Alert API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: Alert
  description: ''
paths:
  /alerts:
    get:
      tags:
      - Alert
      description: Retrieves alert history
      parameters:
      - name: LookbackDays
        in: query
        schema:
          type: integer
          format: int32
          default: 90
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertHistory'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertHistory'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertHistory'
        '429':
          description: If the user has sent too many requests
      summary: Get alerts
      x-summary-source: derived
      operationId: getAlerts
      x-operation-id-source: derived
components:
  schemas:
    AlertHistory:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type: string
          format: uuid
        alertDate:
          type: string
          format: date-time
        value:
          type: number
          format: double
        time:
          type: string
          format: date-time
        alertMessage:
          type:
          - string
          - 'null'
        alertDefinitionId:
          type: string
          format: uuid
        targetIndicatorProvider:
          type:
          - string
          - 'null'
          format: uuid
        targetIndicatorProviderId:
          type:
          - string
          - 'null'
        targetForecastModelId:
          type:
          - string
          - 'null'
          format: uuid
        containingEntityType:
          type:
          - string
          - 'null'
        containingEntityId:
          type:
          - string
          - 'null'
          format: uuid
        contextMessages:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
