openapi: 3.2.0
info:
  title: Board Foresight API - V1 User Context API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: User Context
  description: ''
paths:
  /company:
    get:
      tags:
      - User Context
      summary: Retrieves all companies for authenticated user
      description: The company information associated with the user
      responses:
        '200':
          description: If the companies were retrieved successfully
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
        '429':
          description: If the user has sent too many requests
        '401':
          description: If the user isn't authenticated
        '403':
          description: If the user isn't authorized for such action
      operationId: getCompany
      x-operation-id-source: derived
  /company/{CompanyId}:
    put:
      tags:
      - User Context
      description: Switch company context
      parameters:
      - name: CompanyId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '429':
          description: If the user has sent too many requests
      summary: Replace company by company id
      x-summary-source: derived
      operationId: putCompanyByCompanyId
      x-operation-id-source: derived
components:
  schemas:
    Company:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        prefix:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        createDate:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
      additionalProperties: false
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
