openapi: 3.2.0
info:
  title: Board Foresight API - V1 Alert Definition API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: AlertDefinition
  description: ''
paths:
  /alertdefinitions:
    get:
      tags:
      - AlertDefinition
      description: Retrieves all the alert definitions for the current company.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertDefinition'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertDefinition'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertDefinition'
        '429':
          description: If the user has sent too many requests
      summary: Get alertdefinitions
      x-summary-source: derived
      operationId: getAlertdefinitions
      x-operation-id-source: derived
  /{id}:
    get:
      tags:
      - AlertDefinition
      description: Retrieves the alert definition for the given alert definition ID.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '429':
          description: If the user has sent too many requests
      summary: Get by id
      x-summary-source: derived
      operationId: getById
      x-operation-id-source: derived
components:
  schemas:
    ProviderAccess:
      enum:
      - 0
      - 1
      - 2
      type: integer
      format: int32
    Provider:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        source:
          type:
          - string
          - 'null'
      additionalProperties: false
    IndicatorType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      type: integer
      format: int32
    Seasonality:
      enum:
      - 0
      - 1
      - 999
      type: integer
      format: int32
    Classification:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      type: integer
      format: int32
    Calculation:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      type: integer
      description: 'The transformation applied to the data.



        Possible options:



        None 1



        PeriodOverPeriod 2



        YearOverYear 3



        ThreePeriodYearOverYear 6'
      format: int32
    PeriodAlignment:
      enum:
      - 0
      - 1
      - 2
      type: integer
      format: int32
    Frequency:
      enum:
      - 0
      - 1
      - 2
      - 4
      - 12
      - 52
      - 365
      - 1000
      type: integer
      description: 'The frequency of the data.



        Daily: 365



        Weekly: 52



        Monthly: 12



        Quarterly: 4



        SemiAnnual: 2



        Annual: 1'
      format: int32
    AlertDefinition:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        createDate:
          type: string
          format: date-time
        createdBy:
          type:
          - string
          - 'null'
        owner:
          type:
          - string
          - 'null'
        lastModifiedDate:
          type: string
          format: date-time
        targetIndicator:
          $ref: '#/components/schemas/Indicator'
        targetForecastModelId:
          type:
          - string
          - 'null'
          format: uuid
        calculationType:
          $ref: '#/components/schemas/Calculation'
        comparer:
          type:
          - string
          - 'null'
        threshold:
          type: number
          format: double
        timeframe:
          type: integer
          format: int32
        companyId:
          type:
          - string
          - 'null'
        startDate:
          type:
          - string
          - 'null'
          format: date-time
        notificationEmails:
          type:
          - array
          - 'null'
          items:
            type: string
        notes:
          type:
          - string
          - 'null'
        containingEntityId:
          type:
          - string
          - 'null'
          format: uuid
        containingEntityType:
          type:
          - string
          - 'null'
      additionalProperties: false
    IndustryCode:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
      additionalProperties: false
    AggregationMethod:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    DisplayInformation:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: The display name to be used in the application. Limited to 50 characters.
        description:
          type:
          - string
          - 'null'
          description: The description to be shown in the application. Limited to 1,000 characters.
        color:
          type:
          - string
          - 'null'
          description: The color to use in the application. Must be a valid hex color code.
        category:
          type:
          - string
          - 'null'
          description: The category of the indicator. Limited to 1,000 characters.
      additionalProperties: false
    Indicator:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        aggregate:
          $ref: '#/components/schemas/AggregationMethod'
        calculation:
          $ref: '#/components/schemas/Calculation'
        color:
          type:
          - string
          - 'null'
        displayInformation:
          $ref: '#/components/schemas/DisplayInformation'
        count:
          type: integer
          format: int32
        created:
          type: string
          format: date-time
        startTime:
          type:
          - string
          - 'null'
          format: date-time
        endTime:
          type:
          - string
          - 'null'
          format: date-time
        transformedStartTime:
          type:
          - string
          - 'null'
          format: date-time
        transformedEndTime:
          type:
          - string
          - 'null'
          format: date-time
        frequency:
          $ref: '#/components/schemas/Frequency'
        deprecated:
          type: boolean
        deprecationReason:
          type:
          - string
          - 'null'
        lastModified:
          type: string
          format: date-time
        provider:
          $ref: '#/components/schemas/Provider'
        providerId:
          type:
          - string
          - 'null'
        seasonality:
          $ref: '#/components/schemas/Seasonality'
        source:
          type:
          - string
          - 'null'
        classification:
          $ref: '#/components/schemas/Classification'
        tags:
          type:
          - array
          - 'null'
          items:
            type: string
        type:
          type:
          - string
          - 'null'
        units:
          type:
          - string
          - 'null'
        accessibility:
          $ref: '#/components/schemas/ProviderAccess'
        periodAlignment:
          $ref: '#/components/schemas/PeriodAlignment'
        path:
          type:
          - string
          - 'null'
        notes:
          type:
          - string
          - 'null'
        citation:
          type:
          - string
          - 'null'
        dataSources:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IndicatorDataSource'
        industryCodes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IndustryCode'
        hasZeroVariance:
          type:
          - boolean
          - 'null'
        interval:
          type:
          - string
          - 'null'
        countryCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    IndicatorDataSource:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        url:
          type:
          - string
          - 'null'
        dataSourceType:
          $ref: '#/components/schemas/IndicatorType'
      additionalProperties: false
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
