openapi: 3.2.0
info:
  title: Board Foresight API - V1 Provider API
  description: ''
  version: v1
security:
- api key: []
tags:
- name: Provider
  description: ''
paths:
  /provider:
    get:
      tags:
      - Provider
      description: Retrieves complete list of providers with data in the system. A provider is an entity or organization that publishes indicator data
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
        '429':
          description: If the user has sent too many requests
      summary: Get provider
      x-summary-source: derived
      operationId: getProvider
      x-operation-id-source: derived
components:
  schemas:
    Provider:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        source:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    api_key:
      type: apiKey
      name: ApiKey
      in: query
